-- MySQL Script generated by MySQL Workbench
-- Ter 20 Fev 2018 13:51:18 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `cd_usuario` VARCHAR(32) NOT NULL,
  `nm_senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_usuario`),
  UNIQUE INDEX `cd_usuario_UNIQUE` (`cd_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_campanha` (
  `cd_campanha` INT NOT NULL,
  `nm_campanha` VARCHAR(100) NOT NULL,
  `dsc_campanha` TEXT NULL,
  `img_campanha` BLOB NULL,
  `is_anonimo` TINYINT NOT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_fim` DATE NOT NULL,
  PRIMARY KEY (`cd_campanha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_candidato` (
  `cd_candidato` INT NOT NULL,
  `cd_campanha` INT NOT NULL,
  `nm_candidato` VARCHAR(100) NOT NULL,
  `dsc_candidato` TEXT NULL,
  `img_candidato` BLOB NULL,
  PRIMARY KEY (`cd_candidato`),
  INDEX `fk_candidato_campanha_idx` (`cd_campanha` ASC),
  CONSTRAINT `fk_candidato_campanha`
    FOREIGN KEY (`cd_campanha`)
    REFERENCES `mydb`.`tb_campanha` (`cd_campanha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_voto` (
  `cd_voto` INT NOT NULL,
  `cd_candidato` INT NOT NULL,
  `cd_usuario` VARCHAR(32) NOT NULL,
  `nm_voto` VARCHAR(100) NULL,
  PRIMARY KEY (`cd_voto`),
  INDEX `fk_voto_candidato_idx` (`cd_candidato` ASC),
  INDEX `fk_voto_usuario_idx` (`cd_usuario` ASC),
  CONSTRAINT `fk_voto_candidato`
    FOREIGN KEY (`cd_candidato`)
    REFERENCES `mydb`.`tb_candidato` (`cd_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_usuario`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
